
const API_ERROR_TYPE = {
    INVALID_USERNAME_LENGTH: 'INVALID_USERNAME_LENGTH',
    INVALID_ID_LENGTH: 'INVALID_ID_LENGTH',
    INVALID_PASSWORD_LENGTH: 'INVALID_PASSWORD_LENGTH',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    USER_AUTHENTICATION_ERROR: 'USER_AUTHENTICATION_ERROR'
} as const;

export type API_ERROR_TYPE = typeof API_ERROR_TYPE[keyof typeof API_ERROR_TYPE];